import argparse
import sys
import os

project_root = os.path.dirname(os.path.abspath(__file__))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

def main():
    parser = argparse.ArgumentParser(
        description="Poker RL Agent: Train, simulate, analyze, or run the UI.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    subparsers = parser.add_subparsers(dest="command", required=True,
                                       help="Sub-command to run:\n"
                                            "  train    - Train the RL agent.\n"
                                            "  simulate - Simulate games with a trained agent.\n"
                                            "  analyze  - Analyze detailed simulation logs.\n"
                                            "  ui       - Run the graphical user interface.")

    train_parser = subparsers.add_parser("train", help="Train the RL agent.")
    train_parser.add_argument(
        "--episodes", type=int, default=100000,
        help="Total number of training tournaments (episodes)."
    )
    train_parser.add_argument(
        "--random", type=str, default=None,
        help="Tournament range for using random policy for opponent 1 (format: start-end)."
    )
    train_parser.add_argument(
        "--variable", action="store_true",
        help="Enable variable training mode for opponent 1 (switch between model and random periodically)."
    )
    train_parser.add_argument(
        "--resume", type=str, default=None,
        help="Path to an existing model checkpoint file (.pt) to resume training from."
    )

    simulate_parser = subparsers.add_parser("simulate", help="Simulate/evaluate the trained RL agent.")
    simulate_parser.add_argument(
        "--checkpoint", type=str, required=True,
        help="Path to the trained model checkpoint (.pt) REQUIRED for simulation."
    )
    simulate_parser.add_argument(
        "--episodes", type=int, default=10,
        help="Number of simulation episodes (tournaments) to run."
    )
    simulate_parser.add_argument(
        "--opponent", type=str, default="model", choices=["model", "random", "variable"],
        help="Default type of opponent to use if --seat_config is not provided."
    )
    simulate_parser.add_argument(
        "--seat_config", type=str, default="",
        help="Comma-separated list for each seat (0 to NUM_PLAYERS-1). "
             "Seat 0 must be 'agent'; others can be 'model', 'random', 'variable', or 'empty'."
    )
    simulate_parser.add_argument(
        "--detailed_log", type=str, default="detailed_simulation_log.csv",
        help="Path to the CSV file to store detailed game state and action logs."
    )
    simulate_parser.add_argument(
        "--output_csv", type=str, default="simulation_results.csv",
         help="Path to the CSV file to store simulation summary results."
    )

    analyze_parser = subparsers.add_parser("analyze", help="Analyze detailed simulation logs and compare decisions.")
    analyze_parser.add_argument(
        "--detailed_log", type=str, default="detailed_simulation_log.csv", required=True,
        help="Path to the detailed simulation log CSV file generated by 'simulate'."
    )
    analyze_parser.add_argument(
        "--output_analysis", type=str, default="decision_analysis_summary.csv",
        help="Path to save the analysis summary."
    )
    analyze_parser.add_argument(
        "--agent_id", type=int, default=1,
        help="Player ID (1-based) of the agent to analyze."
    )

    ui_parser = subparsers.add_parser("ui", help="Run the graphical user interface.")
    ui_parser.add_argument(
        "--theme", type=str, default="dark", choices=["dark", "light"],
        help="UI theme to use (dark or light)"
    )
    ui_parser.add_argument(
        "--animation_speed", type=float, default=1.0,
        help="Animation speed multiplier (0.5 = half speed, 2.0 = double speed)"
    )
    ui_parser.add_argument(
        "--fullscreen", action="store_true",
        help="Launch the UI in fullscreen mode"
    )

    args = parser.parse_args()

    if args.command == "train":
        try:
            from Scripts.train import Train
        except ImportError:
            try:
                from Scripts.train import Train
            except ImportError as e:
                print(f"Error: Could not import Train: {e}")
                print("Ensure the folder structure is correct and __init__.py exists if needed.")
                sys.exit(1)

        print("Starting training process...")
        trainer = Train(
            episodes=args.episodes,
            random_range=args.random,
            variable_mode=args.variable,
            resume_from=args.resume
        )
        trainer.run()
        print("Training finished.")

    elif args.command == "simulate":
        print("Starting simulation process...")
        new_argv = [sys.argv[0]]
        new_argv += ["--checkpoint", args.checkpoint]
        new_argv += ["--episodes", str(args.episodes)]
        new_argv += ["--opponent", args.opponent]
        if args.seat_config:
            new_argv += ["--seat_config", args.seat_config]
        if args.detailed_log:
            new_argv += ["--detailed_log", args.detailed_log]
        if args.output_csv:
             new_argv += ["--output_csv", args.output_csv]

        original_argv = sys.argv
        simulate_script_path = os.path.join(project_root, 'Back_End', 'Scripts', 'simulate.py')
        sys.argv = [simulate_script_path] + new_argv[1:]

        try:
            try:
                from Scripts.simulate import main as simulate_main
            except ImportError:
                from Scripts.simulate import main as simulate_main
            simulate_main()
        except ImportError as e:
             print(f"Error: Could not import simulate: {e}")
             print("Ensure the folder structure is correct and __init__.py exists if needed.")
             sys.exit(1)
        except SystemExit as e:
             if e.code != 0: print(f"Exiting due to error in simulate script (code: {e.code}).")
        finally:
             sys.argv = original_argv
        print("Simulation finished.")

    elif args.command == "analyze":
        print("Starting analysis process...")
        new_argv = [sys.argv[0]]
        new_argv += ["--detailed_log", args.detailed_log]
        new_argv += ["--output_analysis", args.output_analysis]
        new_argv += ["--agent_id", str(args.agent_id)]

        original_argv = sys.argv
        analyze_script_path = os.path.join(project_root, 'Back_End', 'Scripts', 'decision_analysis.py')
        sys.argv = [analyze_script_path] + new_argv[1:]

        try:
            try:
                from Scripts.decision_analysis import main as analyze_main
            except ImportError:
                from Scripts.decision_analysis import main as analyze_main
            analyze_main()
        except ImportError as e:
             print(f"Error: Could not import decision_analysis: {e}")
             print("Ensure the folder structure is correct and __init__.py exists if needed.")
             sys.exit(1)
        except SystemExit as e:
             if e.code != 0: print(f"Exiting due to error in analysis script (code: {e.code}).")
        finally:
             sys.argv = original_argv
        print("Analysis finished.")

    elif args.command == "ui":
        print("Launching Enhanced Poker UI...")
        try:
            import tkinter as tk
            try:
                from Front_End.main_ui import PokerApp
            except ImportError:
                from Front_End.main_ui import PokerApp
        except ImportError as e:
            print(f"Error: Could not import UI components: {e}")
            print("Ensure tkinter is installed and the folder structure is correct.")
            sys.exit(1)

        try:
            root = tk.Tk()
            root.withdraw()
            
            root.title("Enhanced Poker Game")
            
            if args.fullscreen:
                root.attributes('-fullscreen', True)
            
            app = PokerApp(root)
            
            if hasattr(app, 'animation_manager') and hasattr(args, 'animation_speed'):
                app.animation_manager.set_animation_speed(args.animation_speed)
            
            root.deiconify()
            root.mainloop()
        except Exception as e:
            print(f"Error launching enhanced UI: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)
        print("UI closed.")

    else:
        parser.print_help()

if __name__ == "__main__":
    main()
