"""
main.py

Unified interface for running Poker RL Agent commands: train, simulate, analyze.

MODIFIED (Gymnasium Adaptation):
- Simplified 'train' command handling:
    - Removed torch.load and model monkey-patching logic for checkpoints.
    - Passes the checkpoint path directly to train.Train() via the 'resume_from'
      argument, as train.py now handles resuming internally.
- Kept 'simulate' and 'analyze' command handling using sys.argv rebuilding,
  but added comments suggesting potential future improvements.
"""

import argparse
import sys
import torch  # Still potentially needed by imported modules indirectly

def main():
    parser = argparse.ArgumentParser(
        description="Poker RL Agent: Train, simulate, or analyze the RL agent using a unified interface."
    )
    subparsers = parser.add_subparsers(dest="command", required=True,
                                       help="Sub-command to run: 'train', 'simulate', or 'analyze'.")

    # --- Subparser for training ---
    train_parser = subparsers.add_parser("train", help="Train the RL agent.")
    train_parser.add_argument(
        "--episodes", type=int, default=100000, # Default from original
        help="Total number of training episodes."
    )
    train_parser.add_argument(
        "--random", type=str, default=None,
        help="Episode range for using random policy for opponent 1 (format: start-end)."
    )
    train_parser.add_argument(
        "--variable", action="store_true",
        help="Enable variable training mode for opponent 1 (switch between model and random periodically)."
    )
    # Changed argument name from --checkpoint to --resume for clarity, matching train.py
    train_parser.add_argument(
        "--resume", type=str, default=None, # Default is None (start fresh)
        help="Path to an existing model checkpoint file (.pt) to resume training from."
    )

    # --- Subparser for simulation/evaluation ---
    simulate_parser = subparsers.add_parser("simulate", help="Simulate/evaluate the trained RL agent.")
    simulate_parser.add_argument(
        "--checkpoint", type=str, default="", required=True, # Make checkpoint required for simulation
        help="Path to the trained model checkpoint (.pt) REQUIRED for simulation."
    )
    simulate_parser.add_argument(
        "--episodes", type=int, default=10,
        help="Number of simulation episodes to run."
    )
    simulate_parser.add_argument(
        "--opponent", type=str, default="model", choices=["model", "random", "variable"],
        help="Default type of opponent to use if --seat_config is not provided."
    )
    simulate_parser.add_argument(
        "--seat_config", type=str, default="",
        help="Comma-separated list for each seat (0 to NUM_PLAYERS-1). "
             "Seat 0 must be 'agent'; others can be 'model', 'random', or 'variable'."
    )
    simulate_parser.add_argument(
        "--detailed_log", type=str, default="detailed_simulation_log.csv",
        help="Path to the CSV file to store detailed game state and action logs."
    )

    # --- Subparser for decision analysis ---
    analyze_parser = subparsers.add_parser("analyze", help="Analyze detailed simulation logs and compare decisions.")
    analyze_parser.add_argument(
        "--detailed_log", type=str, default="detailed_simulation_log.csv", required=True,
        help="Path to the detailed simulation log CSV file generated by 'simulate'."
    )
    analyze_parser.add_argument(
        "--output_analysis", type=str, default="decision_analysis_summary.csv",
        help="Path to save the analysis summary."
    )

    args = parser.parse_args()

    # --- Execute Commands ---
    if args.command == "train":
        try:
            # Import the updated Train class
            from train import Train
        except ImportError:
            print("Error: Could not import Train from train.py. Ensure train.py exists and is updated.")
            sys.exit(1)

        print("Starting training process...")
        # Initialize Train with argparse arguments.
        # Pass the --resume argument directly to the Train class constructor.
        trainer = Train(
            episodes=args.episodes,
            random_range=args.random,
            variable_mode=args.variable,
            resume_from=args.resume # Pass checkpoint path here
        )
        trainer.run()
        print("Training finished.")

    elif args.command == "simulate":
        print("Starting simulation process...")
        # Rebuild sys.argv so that simulate.py receives its expected arguments.
        # NOTE: This method works but is less robust than directly calling a
        # function in simulate.py with arguments. Consider refactoring simulate.py
        # in the future to accept arguments via a function call instead of parsing sys.argv.
        new_argv = [sys.argv[0]] # Script name
        new_argv += ["--checkpoint", args.checkpoint]
        new_argv += ["--episodes", str(args.episodes)]
        new_argv += ["--opponent", args.opponent]
        if args.seat_config:
            new_argv += ["--seat_config", args.seat_config]
        if args.detailed_log:
            new_argv += ["--detailed_log", args.detailed_log]
        # Overwrite sys.argv for the simulate script's internal argparse
        original_argv = sys.argv
        sys.argv = new_argv
        try:
            from simulate import main as simulate_main
            simulate_main()
        except ImportError:
             print("Error: Could not import main from simulate.py. Ensure simulate.py exists and is updated.")
             sys.exit(1)
        finally:
             sys.argv = original_argv # Restore original argv
        print("Simulation finished.")

    elif args.command == "analyze":
        print("Starting analysis process...")
        # Rebuild sys.argv for decision_analysis.py
        # NOTE: Similar comment as for simulate applies here regarding sys.argv rebuilding.
        new_argv = [sys.argv[0]] # Script name
        new_argv += ["--detailed_log", args.detailed_log]
        new_argv += ["--output_analysis", args.output_analysis]
        # Overwrite sys.argv for the analysis script's internal argparse
        original_argv = sys.argv
        sys.argv = new_argv
        try:
            from decision_analysis import main as analyze_main
            analyze_main()
        except ImportError:
             print("Error: Could not import main from decision_analysis.py. Ensure decision_analysis.py exists.")
             sys.exit(1)
        finally:
             sys.argv = original_argv # Restore original argv
        print("Analysis finished.")

    else:
        # This case should not be reached due to subparsers(required=True)
        parser.print_help()

if __name__ == "__main__":
    main()
